### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by dzakisalman** [bagusindrayana/roastgithub#1]
Kenapa ya waktu saya coba pake username lainnya pada pake bahasa gaul indonesia, tapi waktu pake username saya sendiri "mdzsisme" malah pake bahasa inggris sendiri. Udah dicoba berkali-kali juga tetep bahasa inggris, jadi kurang ngena roastingnya.

**Comment by bagusindrayana** [comment]
Ahh iya, soalnya di backendnya dibuat kalau location di profile githubnya bukan Indo bakal jadi bahasa inggris

**Comment by bagusindrayana** [comment]
jadi locationnya harus ada tulisan "Indonesia", waluapun kota2 di Indo tetep gak bakal ke detek Indonesia

**Comment by dzakisalman** [comment]
Ahh i see, makasih kak.
