### ISSUE TITLE
URL https://roastgithub.netlify.app/ diblokir oleh Google Safe Browsing

### ISSUE THREAD

**Issue by Reno-Sifana** [bagusindrayana/roastgithub#2]
@bagusindrayana izin menginformasikan bahwa URL https://roastgithub.netlify.app/ telah diblokiir oleh Google Safe Browsing di Google Chrome 127 
![Screenshot 2024-08-03 223342](https://github.com/user-attachments/assets/0f4795b0-a417-4c85-8d22-06f2a1030137)
ini hasil dari scan di situs web virustotal.com https://www.virustotal.com/gui/url/2cc724e17c4e7ad16170a8d70d13cdbf27177fd931af3a8540bb28c547f2281a 
![Screenshot 2024-08-03 223413](https://github.com/user-attachments/assets/13b1e5b3-c2b9-402a-87d5-a960ecf0acfb)

**Comment by codenoid** [comment]
wkwkwk ada yang sakit hati kayanya karena hasil roastingnya

alternative: https://github-roast.pages.dev

**Comment by bagusindrayana** [comment]
ya bisa coba yang saya deploy di vercel : https://roastgithub.vercel.app
